name: cwt_ecommerce
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

#?-----------------------PACKAGES-----------------------#
dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.15.8
  connectivity_plus: ^5.0.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.17.8
  firebase_core: null
  firebase_storage: ^11.6.9
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  flutter_rating_bar: ^4.0.1
  get: ^4.6.6
  get_storage: ^2.1.1
  google_sign_in: ^6.2.1
  httpp: ^0.0.7
  iconsax: ^0.0.8
  image_picker: ^1.0.8
  intl: ^0.19.0
  logger: ^2.2.0
  lottie: ^3.0.0
  readmore: ^3.0.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
