name: cwt_ecommerce
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

#?-----------------------PACKAGES-----------------------#
dependencies:
  flutter:
    sdk: flutter

  #? State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  #? Utility Package
  httpp: ^0.0.7
  intl: ^0.19.0
  logger: ^2.2.0
  url_launcher: ^6.2.5
  carousel_slider: ^4.2.1
  flutter_native_splash: ^2.3.11
  smooth_page_indicator: ^1.1.0

  #? Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logos/
    - assets/images/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/icons/categories/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
