// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOUVAO4FlXGXnufdwG3NHj3ieFnPtMnCo',
    appId: '1:629707389478:web:05aae421cec927a45444e7',
    messagingSenderId: '629707389478',
    projectId: 'cwt-ecommerce-3c3a8',
    authDomain: 'cwt-ecommerce-3c3a8.firebaseapp.com',
    storageBucket: 'cwt-ecommerce-3c3a8.appspot.com',
    measurementId: 'G-5YGJJ5E7L7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF1CjqC4Vfq4Z04UYL6_gF__OoKoKzUBk',
    appId: '1:629707389478:android:dff9e556eae704ef5444e7',
    messagingSenderId: '629707389478',
    projectId: 'cwt-ecommerce-3c3a8',
    storageBucket: 'cwt-ecommerce-3c3a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmcvM1UjWLWc5wq50-lfhA8JquDkJNs6k',
    appId: '1:629707389478:ios:f659392263c43db55444e7',
    messagingSenderId: '629707389478',
    projectId: 'cwt-ecommerce-3c3a8',
    storageBucket: 'cwt-ecommerce-3c3a8.appspot.com',
    iosClientId: '629707389478-a2vs6uf4v2ahm9hk581ufd2e38vkfdvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwtEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmcvM1UjWLWc5wq50-lfhA8JquDkJNs6k',
    appId: '1:629707389478:ios:f659392263c43db55444e7',
    messagingSenderId: '629707389478',
    projectId: 'cwt-ecommerce-3c3a8',
    storageBucket: 'cwt-ecommerce-3c3a8.appspot.com',
    iosClientId: '629707389478-a2vs6uf4v2ahm9hk581ufd2e38vkfdvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwtEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOUVAO4FlXGXnufdwG3NHj3ieFnPtMnCo',
    appId: '1:629707389478:web:767e497df8b012c15444e7',
    messagingSenderId: '629707389478',
    projectId: 'cwt-ecommerce-3c3a8',
    authDomain: 'cwt-ecommerce-3c3a8.firebaseapp.com',
    storageBucket: 'cwt-ecommerce-3c3a8.appspot.com',
    measurementId: 'G-Y812MMLNKL',
  );

}